server:
  port: 8030
spring:
  application:
    name: client
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
  cloud:
    inetutils:
      # 忽略指定网卡，支持正则表达式（这里使用正则表达式忽略所有虚拟机网卡）
      ignoredInterfaces: ['VMware.*']
eureka:
  client:
    service-url:
      defaultZone: http://192.168.234.130:8761/eureka/
  instance:
    prefer-ip-address: true

ribbon:
  ConnetctTimeout: 5000
  ReadTimeout: 5000
  eureka:
    enabled: true
